Repository DbUp/DbUp, pull requests merged in 2023-08, with the labels that each got.

#697 Upgrade Microsoft.Data.SqlClient from 5.0.1 to 5.1.1
  src/dbup-sqlserver/dbup-sqlserver.csproj
Labels: dependencies, bugfix

#704 Update README
  README.md
  docs/more-info/schema-downgrading.md
Labels: documentation

#707 Bump packages for tests/samples
  src/Samples/FirebirdSampleApplication/FirebirdSampleApplication.csproj
  src/Samples/SQLiteSampleApplication/SQLiteSampleApplication.csproj
  src/Samples/SampleApplication/SampleApplication.csproj
  src/Tests.Common/Tests.Common.csproj
  src/dbup-sqlite/dbup-sqlite.csproj
  src/dbup-tests/Support/MySql/MySqlSupportTests.CanHandleDelimiter.approved.txt
  src/dbup-tests/Support/MySql/MySqlSupportTests.cs
  src/dbup-tests/dbup-tests.csproj
Labels: dependencies

#644 Fix InvalidCastException on DB existence check (CockhroachDb)
  src/dbup-core/Support/TableJournal.cs
  src/dbup-postgresql/PostgresqlExtensions.cs
  src/dbup-sqlserver/SqlServerExtensions.cs
Labels: dbup-postgresql, dbup-sqlserver, bugfix

#528 Pass script options to embeddedScriptProvider
  src/dbup-core/ScriptProviders/EmbeddedScriptAndCodeProvider.cs
Labels: bugfix

#608 Make DoesTableExist virtual
  src/dbup-core/Support/TableJournal.cs
Labels: dbup-core

#712 Add badges for issues into README
  README.md
Labels: documentation

#629 Add support for positional parameters and disabling SQL Rewriting when using PostgreSQL
  src/dbup-core/Support/TableJournal.cs
  src/dbup-postgresql/PostgresqlTableJournal.cs
  src/dbup-tests/ApprovalFiles/dbup-core.approved.cs
  src/dbup-tests/Support/Postgresql/ApprovalFiles/dbup-postgresql.approved.cs
  src/dbup-tests/Support/Postgresql/PostgresTableJournalTests.cs
Labels: dbup-postgresql

#584 chore (Project): Whitespace and empty line tidy . Roslynator RCS1037
  src/Samples/SampleApplication/Program.cs
  src/dbup-core/Builder/StandardExtensions.cs
  src/dbup-core/Engine/LazySqlScript.cs
  src/dbup-core/Engine/Preprocessors/VariableSubstitutionPreprocessor.cs
  src/dbup-core/Engine/SqlScript.cs
  src/dbup-core/Engine/UpgradeEngine.cs
  src/dbup-core/Helpers/AdHocSqlRunner.cs
  src/dbup-core/Helpers/OctopusDeployExtensions.cs
  src/dbup-core/Helpers/UpgradeEngineHtmlReport.cs
  src/dbup-core/Properties/JetbrainsAnnotations.cs
  src/dbup-core/ScriptProviders/EmbeddedScriptAndCodeProvider.cs
  src/dbup-core/ScriptProviders/EmbeddedScriptsProvider.cs
  src/dbup-core/ScriptProviders/FileSystemScriptProvider.cs
  src/dbup-core/ScriptProviders/ScriptInstanceProvider.cs
  src/dbup-core/Support/ScriptExecutor.cs
  src/dbup-core/Support/SqlCommandReader.cs
  src/dbup-core/Support/SqlParser.cs
  src/dbup-firebird/FirebirdTableJournal.cs
  src/dbup-mysql/MySqlCommandSplitter.cs
  src/dbup-mysql/MySqlConnectionManager.cs
  src/dbup-mysql/MySqlExtensions.cs
  src/dbup-mysql/MySqlScriptExecutor.cs
  src/dbup-mysql/MySqlTableJournal.cs
  src/dbup-oracle/OracleScriptExecutor.cs
  src/dbup-postgresql/PostgresqlConnectionManager.cs
  src/dbup-postgresql/PostgresqlExtensions.cs
  src/dbup-postgresql/PostgresqlTableJournal.cs
  src/dbup-sqlanywhere/SqlAnywhereConnectionManager.cs
  src/dbup-sqlanywhere/SqlAnywhereExtensions.cs
  src/dbup-sqlanywhere/SqlAnywhereObjectParser.cs
  src/dbup-sqlanywhere/SqlAnywhereScriptExecutor.cs
  src/dbup-sqlanywhere/SqlAnywhereTableJournal.cs
  src/dbup-sqlce/SqlCeTableJournal.cs
  src/dbup-sqlite/Helpers/SharedConnection.cs
  src/dbup-sqlite/SQLiteScriptExecutor.cs
  src/dbup-sqlite/SQLiteTableJournal.cs
  src/dbup-sqlserver/SqlServerExtensions.cs
  src/dbup-sqlserver/SqlServerObjectParser.cs
  src/dbup-sqlserver/SqlTableJournal.cs
  src/dbup-tests/Engine/Output/LoggingTests.cs
  src/dbup-tests/Helpers/FilterFactoryTests.cs
  src/dbup-tests/Support/MySql/MySqlConnectionManagerTests.cs
  src/dbup-tests/Support/MySql/MySqlSupportTests.cs
  src/dbup-tests/Support/SqlServer/SqlCommandSplitterTests.cs
Labels: code style, needs confirmation
